source "https://rubygems.org"

gem "haml"
gem "roda"

gem "redis"

# gem "bitcoin-client", path: "~/apps/bitcoin-client"
# gem "bitcoin-client", github: "makevoid/bitcoin-client"
gem "bitcoin-client", git: "https://github.com/makevoid/bitcoin-client"
